diff --git a/hardware/Huawei_Atlas800TA3/Megatron-LM/examples/post_training/modelopt/Dockerfile.patch b/hardware/Huawei_Atlas800TA3/Megatron-LM/examples/post_training/modelopt/Dockerfile.patch
new file mode 100644
index 00000000..de15344b
--- /dev/null
+++ b/hardware/Huawei_Atlas800TA3/Megatron-LM/examples/post_training/modelopt/Dockerfile.patch
@@ -0,0 +1,24 @@
+diff --git a/examples/post_training/modelopt/Dockerfile b/examples/post_training/modelopt/Dockerfile
+new file mode 100644
+index 000000000..e0b4f0002
+--- /dev/null
++++ b/examples/post_training/modelopt/Dockerfile
+@@ -0,0 +1,17 @@
++FROM nvcr.io/nvidia/pytorch:25.06-py3
++
++ARG PIP_CONSTRAINT=
++
++WORKDIR /workspace/nmm-sandbox
++
++RUN pip install jsonlines omegaconf pulp torchprofile
++RUN pip install flask flask_restful fire nltk
++RUN pip install tiktoken blobfile
++
++RUN pip install datasets transformers
++
++RUN pip install triton==3.3.1
++RUN pip install git+https://github.com/state-spaces/mamba.git
++RUN pip install git+https://github.com/Dao-AILab/causal-conv1d.git
++
++RUN pip install -U nvidia-modelopt
+

